name: holoscan
channels:
  - conda-forge
  - nvidia
  - rapidsai
dependencies:
  - python=3.11
  - cupy
  - cusignal
  - numpy
  - scipy
  - matplotlib
  - pillow
  - h5py
  - cython
  - pip
  - pip:
      - holoscan
